/**
 * Permission codes. Convention: MODULE_ACTION.
 * These are seeded into the `permissions` table and attached to roles via
 * `role_permissions`. The permissionMiddleware checks a user's resolved
 * permission set (derived from their role) against the code(s) required by
 * a route.
 */
const PERMISSIONS = Object.freeze({
  // Users & RBAC
  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',

  // Organization structure
  ORG_STRUCTURE_VIEW: 'ORG_STRUCTURE_VIEW',
  ORG_STRUCTURE_MANAGE: 'ORG_STRUCTURE_MANAGE',

  // Employees
  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  EMPLOYEE_VIEW_OWN: 'EMPLOYEE_VIEW_OWN',
  EMPLOYEE_MANAGE: 'EMPLOYEE_MANAGE',

  // Shifts / schedules
  SHIFT_VIEW: 'SHIFT_VIEW',
  SHIFT_MANAGE: 'SHIFT_MANAGE',

  // Attendance
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_VIEW_OWN: 'ATTENDANCE_VIEW_OWN',
  ATTENDANCE_VIEW_TEAM: 'ATTENDANCE_VIEW_TEAM',
  ATTENDANCE_MANAGE: 'ATTENDANCE_MANAGE',
  LEAVE_APPROVE: 'LEAVE_APPROVE',

  // Payroll
  PAYROLL_VIEW: 'PAYROLL_VIEW',
  PAYROLL_VIEW_OWN: 'PAYROLL_VIEW_OWN',
  PAYROLL_PROCESS: 'PAYROLL_PROCESS',
  PAYROLL_APPROVE: 'PAYROLL_APPROVE',

  // KPI
  KPI_VIEW: 'KPI_VIEW',
  KPI_MANAGE: 'KPI_MANAGE',
  KPI_RECORD: 'KPI_RECORD',

  // Performance
  PERFORMANCE_VIEW: 'PERFORMANCE_VIEW',
  PERFORMANCE_VIEW_OWN: 'PERFORMANCE_VIEW_OWN',
  PERFORMANCE_VIEW_TEAM: 'PERFORMANCE_VIEW_TEAM',
  PERFORMANCE_MANAGE: 'PERFORMANCE_MANAGE',
  PERFORMANCE_REVIEW: 'PERFORMANCE_REVIEW',

  // Production
  PRODUCTION_VIEW: 'PRODUCTION_VIEW',
  PRODUCTION_MANAGE: 'PRODUCTION_MANAGE',

  // Dashboard & Reports
  DASHBOARD_VIEW_ORG: 'DASHBOARD_VIEW_ORG',
  DASHBOARD_VIEW_DEPARTMENT: 'DASHBOARD_VIEW_DEPARTMENT',
  DASHBOARD_VIEW_OWN: 'DASHBOARD_VIEW_OWN',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // System
  SYSTEM_SETTINGS_MANAGE: 'SYSTEM_SETTINGS_MANAGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
});

const PERMISSION_LIST = Object.values(PERMISSIONS);

/**
 * Default permission-to-role mapping used by the seeder.
 * ADMIN implicitly receives every permission at seed time.
 */
const ROLE_PERMISSION_MAP = {
  ADMIN: PERMISSION_LIST,
  HR_MANAGER: [
    'USER_VIEW',
    'ORG_STRUCTURE_VIEW', 'ORG_STRUCTURE_MANAGE',
    'EMPLOYEE_VIEW', 'EMPLOYEE_MANAGE',
    'SHIFT_VIEW', 'SHIFT_MANAGE',
    'ATTENDANCE_VIEW', 'ATTENDANCE_MANAGE', 'LEAVE_APPROVE',
    'PAYROLL_VIEW', 'PAYROLL_PROCESS', 'PAYROLL_APPROVE',
    'KPI_VIEW', 'KPI_MANAGE', 'KPI_RECORD',
    'PERFORMANCE_VIEW', 'PERFORMANCE_MANAGE', 'PERFORMANCE_REVIEW',
    'PRODUCTION_VIEW',
    'DASHBOARD_VIEW_ORG', 'DASHBOARD_VIEW_DEPARTMENT',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'AUDIT_LOG_VIEW', 'NOTIFICATION_VIEW',
  ],
  MANAGER: [
    'ORG_STRUCTURE_VIEW',
    'EMPLOYEE_VIEW',
    'SHIFT_VIEW',
    'ATTENDANCE_VIEW_TEAM', 'LEAVE_APPROVE',
    'PAYROLL_VIEW_OWN',
    'KPI_VIEW', 'KPI_RECORD',
    'PERFORMANCE_VIEW_TEAM', 'PERFORMANCE_REVIEW',
    'PRODUCTION_VIEW', 'PRODUCTION_MANAGE',
    'DASHBOARD_VIEW_DEPARTMENT', 'DASHBOARD_VIEW_OWN',
    'REPORT_VIEW',
    'NOTIFICATION_VIEW',
  ],
  EMPLOYEE: [
    'EMPLOYEE_VIEW_OWN',
    'ATTENDANCE_VIEW_OWN',
    'PAYROLL_VIEW_OWN',
    'KPI_VIEW',
    'PERFORMANCE_VIEW_OWN',
    'DASHBOARD_VIEW_OWN',
    'NOTIFICATION_VIEW',
  ],
};

module.exports = { PERMISSIONS, PERMISSION_LIST, ROLE_PERMISSION_MAP };