const ATTENDANCE_STATUS = Object.freeze({
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LEAVE: 'LEAVE',
  HALF_DAY: 'HALF_DAY',
  HOLIDAY: 'HOLIDAY',
  OFF_DAY: 'OFF_DAY',
});

const EMPLOYMENT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  ON_LEAVE: 'ON_LEAVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED',
  RESIGNED: 'RESIGNED',
  RETIRED: 'RETIRED',
});

const WORK_SCHEDULE_TYPE = Object.freeze({
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
});

const PAYROLL_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  CALCULATED: 'CALCULATED',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
});

const LEAVE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

const EVALUATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  MANAGER_REVIEWED: 'MANAGER_REVIEWED',
  FINALIZED: 'FINALIZED',
});

const IMPROVEMENT_PLAN_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

const NOTIFICATION_TYPE = Object.freeze({
  INFO: 'INFO',
  ALERT: 'ALERT',
  WARNING: 'WARNING',
  SUCCESS: 'SUCCESS',
});

module.exports = {
  ATTENDANCE_STATUS,
  EMPLOYMENT_STATUS,
  WORK_SCHEDULE_TYPE,
  PAYROLL_STATUS,
  LEAVE_STATUS,
  EVALUATION_STATUS,
  IMPROVEMENT_PLAN_STATUS,
  NOTIFICATION_TYPE,
};